project_id = "xynmvdrxpceiwbglrpuy"

[functions.gladia-session-init]
verify_jwt = false

[functions.sales-copilot-suggest]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
